version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: serverCode/Dockerfile
    container_name: server
    ports:
      - "1099:1099"
    networks:
      - rmi-network
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
    # Remove volumes section if not needed

  client:
    build:
      context: .
      dockerfile: clientCode/Dockerfile
    container_name: client
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
    networks:
      - rmi-network
    # Remove volumes section if not needed

networks:
  rmi-network:
    driver: bridge
